[project]
name = "core_components"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foss-car/core_components"

[build]
clock_type = "posedge"
reset_type = "async_high"
target = {type = "directory", path = "target"}

[test]
simulator = "verilator"

#[test.verilator]
#compile_args = ""
#simulate_args = ""


